name: Deploy Static Website

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Step to check out the repository code

      - name: Set up Node.js
        uses: actions/setup-node@v2  # Set up Node.js environment
        with:
          node-version: '14'  # Specify the Node.js version (optional for static sites)

      - name: Install Firebase CLI
        run: npm install -g firebase-tools  # Install Firebase CLI globally

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}  # Use your Firebase token from GitHub Secrets
        run: |
          firebase deploy --token $FIREBASE_TOKEN  # Deploy using the Firebase token
